#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
./Allclean

restore0Dir

runApplication blockMesh

runApplication setFields

runApplication renumberMesh -overwrite 

runApplication decomposePar

runParallel $(getApplication)

rm -rf dynamicCode

rm myLog/* 
mv log.* myLog/

# # interFoam | tee log.interFoam
# mpirun -np 4 interFoam -parallel | tee log.interFoam
#------------------------------------------------------------------------------
